/**
 * 자동 생성 파일입니다. 수정하려면 semantic-color-tokens.csv 를 고치고 `npm run tokens` 를 실행하세요.
 */

/** 시맨틱 컬러 토큰 메타데이터입니다. 스토리북 팔레트 문서와 테스트에서 사용합니다. */
export interface KoastColorToken {
  category: string;
  token: string;
  cssVar: string;
  light: string;
  dark: string;
}

export const koastColorTokens: readonly KoastColorToken[] = [
  {
    category: 'color/content',
    token: 'primary',
    cssVar: '--koast-content-primary',
    light: '#18181b',
    dark: '#ffffff',
  },
  {
    category: 'color/content',
    token: 'secondary',
    cssVar: '--koast-content-secondary',
    light: '#3f3f46',
    dark: '#f4f4f5',
  },
  {
    category: 'color/content',
    token: 'tertiary',
    cssVar: '--koast-content-tertiary',
    light: '#52525b',
    dark: '#e4e4e7',
  },
  {
    category: 'color/content',
    token: 'subtle',
    cssVar: '--koast-content-subtle',
    light: '#e4e4e7',
    dark: '#52525b',
  },
  {
    category: 'color/content',
    token: 'info',
    cssVar: '--koast-content-info',
    light: '#2563eb',
    dark: '#3b82f6',
  },
  {
    category: 'color/content',
    token: 'warning',
    cssVar: '--koast-content-warning',
    light: '#f59e0b',
    dark: '#fbbf24',
  },
  {
    category: 'color/content',
    token: 'success',
    cssVar: '--koast-content-success',
    light: '#16a34a',
    dark: '#22c55e',
  },
  {
    category: 'color/content',
    token: 'danger',
    cssVar: '--koast-content-danger',
    light: '#dc2626',
    dark: '#ef4444',
  },
  {
    category: 'color/content',
    token: 'info-bold',
    cssVar: '--koast-content-info-bold',
    light: '#1e40af',
    dark: '#93c5fd',
  },
  {
    category: 'color/content',
    token: 'warning-bold',
    cssVar: '--koast-content-warning-bold',
    light: '#d97706',
    dark: '#fcd34d',
  },
  {
    category: 'color/content',
    token: 'success-bold',
    cssVar: '--koast-content-success-bold',
    light: '#166534',
    dark: '#bbf7d0',
  },
  {
    category: 'color/content',
    token: 'danger-bold',
    cssVar: '--koast-content-danger-bold',
    light: '#991b1b',
    dark: '#dc2626',
  },
  {
    category: 'color/content',
    token: 'disabled',
    cssVar: '--koast-content-disabled',
    light: '#71717a',
    dark: '#d4d4d8',
  },
  {
    category: 'color/content/interactive',
    token: 'primary',
    cssVar: '--koast-content-interactive-primary',
    light: 'brand/primary/600',
    dark: 'brand/primary/400',
  },
  {
    category: 'color/content/interactive',
    token: 'primary-hovered',
    cssVar: '--koast-content-interactive-primary-hovered',
    light: 'brand/primary/700',
    dark: 'brand/primary/300',
  },
  {
    category: 'color/content/interactive',
    token: 'primary-pressed',
    cssVar: '--koast-content-interactive-primary-pressed',
    light: 'brand/primary/800',
    dark: 'brand/primary/200',
  },
  {
    category: 'color/content/interactive',
    token: 'secondary',
    cssVar: '--koast-content-interactive-secondary',
    light: 'brand/secondary/600',
    dark: 'brand/secondary/300',
  },
  {
    category: 'color/content/interactive',
    token: 'secondary-hovered',
    cssVar: '--koast-content-interactive-secondary-hovered',
    light: 'brand/secondary/700',
    dark: 'brand/secondary/200',
  },
  {
    category: 'color/content/interactive',
    token: 'secondary-pressed',
    cssVar: '--koast-content-interactive-secondary-pressed',
    light: 'brand/secondary/800',
    dark: 'brand/secondary/100',
  },
  {
    category: 'color/content/interactive',
    token: 'selected',
    cssVar: '--koast-content-interactive-selected',
    light: 'brand/primary/600',
    dark: 'brand/primary/400',
  },
  {
    category: 'color/content/interactive',
    token: 'visited',
    cssVar: '--koast-content-interactive-visited',
    light: '#4f46e5',
    dark: '#6366f1',
  },
  {
    category: 'color/content/interactive',
    token: 'inverse',
    cssVar: '--koast-content-interactive-inverse',
    light: '#ffffff',
    dark: '#18181b',
  },
  {
    category: 'color/bg',
    token: 'primary',
    cssVar: '--koast-bg-primary',
    light: '#ffffff',
    dark: '#18181b',
  },
  {
    category: 'color/bg',
    token: 'secondary',
    cssVar: '--koast-bg-secondary',
    light: '#fafafa',
    dark: '#27272a',
  },
  {
    category: 'color/bg',
    token: 'tertiary',
    cssVar: '--koast-bg-tertiary',
    light: '#f4f4f5',
    dark: '#3f3f46',
  },
  {
    category: 'color/bg',
    token: 'info-subtle',
    cssVar: '--koast-bg-info-subtle',
    light: '#eff6ff',
    dark: '#1e40af',
  },
  {
    category: 'color/bg',
    token: 'info-bold',
    cssVar: '--koast-bg-info-bold',
    light: '#1d4ed8',
    dark: '#60a5fa',
  },
  {
    category: 'color/bg',
    token: 'warning-subtle',
    cssVar: '--koast-bg-warning-subtle',
    light: '#fffbeb',
    dark: '#92400e',
  },
  {
    category: 'color/bg',
    token: 'warning-bold',
    cssVar: '--koast-bg-warning-bold',
    light: '#d97706',
    dark: '#f59e0b',
  },
  {
    category: 'color/bg',
    token: 'success-subtle',
    cssVar: '--koast-bg-success-subtle',
    light: '#f0fdf4',
    dark: '#166534',
  },
  {
    category: 'color/bg',
    token: 'success-bold',
    cssVar: '--koast-bg-success-bold',
    light: '#16a34a',
    dark: '#86efac',
  },
  {
    category: 'color/bg',
    token: 'danger-subtle',
    cssVar: '--koast-bg-danger-subtle',
    light: '#fef2f2',
    dark: '#7f1d1d',
  },
  {
    category: 'color/bg',
    token: 'danger-bold',
    cssVar: '--koast-bg-danger-bold',
    light: '#b91c1c',
    dark: '#f87171',
  },
  {
    category: 'color/bg',
    token: 'disabled',
    cssVar: '--koast-bg-disabled',
    light: '#d4d4d8',
    dark: '#71717a',
  },
  {
    category: 'color/bg',
    token: 'brand',
    cssVar: '--koast-bg-brand',
    light: 'brand/primary/600',
    dark: 'brand/primary/600',
  },
  {
    category: 'color/bg',
    token: 'inverse-bold',
    cssVar: '--koast-bg-inverse-bold',
    light: '#3f3f46',
    dark: '#f4f4f5',
  },
  {
    category: 'color/bg',
    token: 'inverse-bolder',
    cssVar: '--koast-bg-inverse-bolder',
    light: '#27272a',
    dark: '#fafafa',
  },
  {
    category: 'color/bg/interactive',
    token: 'primary',
    cssVar: '--koast-bg-interactive-primary',
    light: 'brand/primary/600',
    dark: 'brand/primary/400',
  },
  {
    category: 'color/bg/interactive',
    token: 'primary-hovered',
    cssVar: '--koast-bg-interactive-primary-hovered',
    light: 'brand/primary/700',
    dark: 'brand/primary/300',
  },
  {
    category: 'color/bg/interactive',
    token: 'primary-pressed',
    cssVar: '--koast-bg-interactive-primary-pressed',
    light: 'brand/primary/800',
    dark: 'brand/primary/200',
  },
  {
    category: 'color/bg/interactive',
    token: 'secondary',
    cssVar: '--koast-bg-interactive-secondary',
    light: 'brand/secondary/50',
    dark: 'brand/secondary/900',
  },
  {
    category: 'color/bg/interactive',
    token: 'secondary-hovered',
    cssVar: '--koast-bg-interactive-secondary-hovered',
    light: 'brand/secondary/200',
    dark: 'brand/secondary/800',
  },
  {
    category: 'color/bg/interactive',
    token: 'secondary-pressed',
    cssVar: '--koast-bg-interactive-secondary-pressed',
    light: 'brand/secondary/300',
    dark: 'brand/secondary/700',
  },
  {
    category: 'color/bg/interactive',
    token: 'selected',
    cssVar: '--koast-bg-interactive-selected',
    light: 'brand/primary/50',
    dark: 'brand/primary/900',
  },
  {
    category: 'color/bg/interactive',
    token: 'selected-hovered',
    cssVar: '--koast-bg-interactive-selected-hovered',
    light: 'brand/primary/100',
    dark: 'brand/primary/800',
  },
  {
    category: 'color/bg/interactive',
    token: 'selected-pressed',
    cssVar: '--koast-bg-interactive-selected-pressed',
    light: 'brand/primary/200',
    dark: 'brand/primary/700',
  },
  {
    category: 'color/bg/interactive',
    token: 'danger',
    cssVar: '--koast-bg-interactive-danger',
    light: '#dc2626',
    dark: '#ef4444',
  },
  {
    category: 'color/bg/interactive',
    token: 'danger-hovered',
    cssVar: '--koast-bg-interactive-danger-hovered',
    light: '#b91c1c',
    dark: '#f87171',
  },
  {
    category: 'color/bg/interactive',
    token: 'danger-pressed',
    cssVar: '--koast-bg-interactive-danger-pressed',
    light: '#991b1b',
    dark: '#fca5a5',
  },
  {
    category: 'color/border',
    token: 'primary',
    cssVar: '--koast-border-primary',
    light: '#a1a1aa',
    dark: '#71717a',
  },
  {
    category: 'color/border',
    token: 'secondary',
    cssVar: '--koast-border-secondary',
    light: '#e4e4e7',
    dark: '#3f3f46',
  },
  {
    category: 'color/border',
    token: 'focus-ring',
    cssVar: '--koast-border-focus-ring',
    light: 'brand/primary/600',
    dark: 'brand/primary/600',
  },
  {
    category: 'color/border',
    token: 'info-subtle',
    cssVar: '--koast-border-info-subtle',
    light: '#eff6ff',
    dark: '#1e40af',
  },
  {
    category: 'color/border',
    token: 'info',
    cssVar: '--koast-border-info',
    light: '#2563eb',
    dark: '#3b82f6',
  },
  {
    category: 'color/border',
    token: 'warning-subtle',
    cssVar: '--koast-border-warning-subtle',
    light: '#fffbeb',
    dark: '#92400e',
  },
  {
    category: 'color/border',
    token: 'warning',
    cssVar: '--koast-border-warning',
    light: '#f59e0b',
    dark: '#fbbf24',
  },
  {
    category: 'color/border',
    token: 'success-subtle',
    cssVar: '--koast-border-success-subtle',
    light: '#f0fdf4',
    dark: '#15803d',
  },
  {
    category: 'color/border',
    token: 'success',
    cssVar: '--koast-border-success',
    light: '#16a34a',
    dark: '#22c55e',
  },
  {
    category: 'color/border',
    token: 'danger-subtle',
    cssVar: '--koast-border-danger-subtle',
    light: '#fef2f2',
    dark: '#991b1b',
  },
  {
    category: 'color/border',
    token: 'danger',
    cssVar: '--koast-border-danger',
    light: '#dc2626',
    dark: '#ef4444',
  },
  {
    category: 'color/border',
    token: 'disabled',
    cssVar: '--koast-border-disabled',
    light: '#a1a1aa',
    dark: '#d4d4d8',
  },
  {
    category: 'color/border/interactive',
    token: 'primary',
    cssVar: '--koast-border-interactive-primary',
    light: 'brand/primary/600',
    dark: 'brand/primary/400',
  },
  {
    category: 'color/border/interactive',
    token: 'primary-hovered',
    cssVar: '--koast-border-interactive-primary-hovered',
    light: 'brand/primary/700',
    dark: 'brand/primary/300',
  },
  {
    category: 'color/border/interactive',
    token: 'primary-pressed',
    cssVar: '--koast-border-interactive-primary-pressed',
    light: 'brand/primary/800',
    dark: 'brand/primary/200',
  },
  {
    category: 'color/border/interactive',
    token: 'secondary',
    cssVar: '--koast-border-interactive-secondary',
    light: 'brand/secondary/400',
    dark: 'brand/secondary/500',
  },
  {
    category: 'color/border/interactive',
    token: 'secondary-hovered',
    cssVar: '--koast-border-interactive-secondary-hovered',
    light: 'brand/secondary/500',
    dark: 'brand/secondary/400',
  },
  {
    category: 'color/border/interactive',
    token: 'secondary-pressed',
    cssVar: '--koast-border-interactive-secondary-pressed',
    light: 'brand/secondary/600',
    dark: 'brand/secondary/300',
  },
  {
    category: 'color/border/interactive',
    token: 'danger',
    cssVar: '--koast-border-interactive-danger',
    light: '#dc2626',
    dark: '#ef4444',
  },
  {
    category: 'color/border/interactive',
    token: 'danger-hovered',
    cssVar: '--koast-border-interactive-danger-hovered',
    light: '#b91c1c',
    dark: '#f87171',
  },
  {
    category: 'color/border/interactive',
    token: 'danger-pressed',
    cssVar: '--koast-border-interactive-danger-pressed',
    light: '#991b1b',
    dark: '#fca5a5',
  },
  {
    category: 'color/media',
    token: 'on-dark',
    cssVar: '--koast-media-on-dark',
    light: '#ffffff',
    dark: '#ffffff',
  },
  {
    category: 'color/media',
    token: 'on-light',
    cssVar: '--koast-media-on-light',
    light: '#18181b',
    dark: '#18181b',
  },
  {
    category: 'color/effect/shadow',
    token: 'cast',
    cssVar: '--koast-shadow-cast',
    light: 'rgba(0,0,0,0.16)',
    dark: 'rgba(0,0,0,0.24)',
  },
  {
    category: 'color/effect/shadow',
    token: 'core',
    cssVar: '--koast-shadow-core',
    light: 'rgba(0,0,0,0.12)',
    dark: 'rgba(0,0,0,0.2)',
  },
];

/** 프로젝트별로 주입 가능한 brand 램프의 단계입니다. */
export const KOAST_BRAND_STEPS = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900'] as const;

export type KoastBrandStep = typeof KOAST_BRAND_STEPS[number];
export type KoastBrandTone = 'primary' | 'secondary';
